### PR TITLE
Adding a Comma and Period option to the settings menu

### PR DESCRIPTION
**Pull request by SaurabhJamadagni**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Hey @andrewtavis, here's one more giant PR again unfortunately 🙈 

The PR adds:
- Lists the installed keyboards
- Displays menu option to toggle between comma and period for keyboards
- Translates the preferences to the keyboard view controller on launching a particular language keyboard.

Regarding the problem I was facing about refreshing the list, it has been worked out in a very hacky manner for the moment. I will explain the problem better in the meeting tomorrow. The gist is that it works when we open the app on some other menu tab and then navigate to the `Settings` tab. This allows me to call the `viewWillAppear` method which takes care of the refresh. The refresh uses the Notification system. Publishes a notification whenever the value changes which is then handled by a function that is set to execute. This function calls the refresh on the child table views. 

I also tried to add a notification observer to only the dynamic data sections so that not all child tables are reloaded. This is done using an additional property `hasDynamicData` which accepts an enum value. Chose an enum since if we add more sections further that have dynamic data, handling it using a switch statement should be easier.

I plan on working on this in the background. But this issue was holding back from moving on to the next issues so I decided to push this unoptimised yet best working state. Do let me know if it is okay for now.

### Related issue

- #196 
- #308

### CODE REVIEW

**Review by andrewtavis — APPROVED** [review]
Changes look good to me, @SaurabhJamadagni 😊 Obviously the hacky behavior of jumping to `Installation` from `Settings` on reload is not ideal, but let's just be sure to have this fixed in the coming weeks when we get ready to release `v3.0.0`. I can also try to look into this when I re-implement the German app localization :)

**Comment by SaurabhJamadagni** [comment]
>  let's just be sure to have this fixed in the coming weeks

@andrewtavis, could you open up an issue for it? I think it would be good to document the changes that follow in case we come across a bug similar to this down the line. Also, should serve as a reminder for us as well. Or I'll create the issue tomorrow if you are occupied. No worries 😄

**Comment by andrewtavis** [comment]
I’ll make the issue now, @SaurabhJamadagni  :)

**Comment by andrewtavis** [comment]
See #344, @SaurabhJamadagni 😊

**Pull request merged**
