### PR TITLE
Removed void_function_in_ternary from disabled rules in .swiftint.yml

### PR DESCRIPTION
**Pull request by mostazomarc**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Removed `void_function_in_ternary` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fixed all errors for it in the codebase.

**The linter fix was tested running: `swiftlint --no-cache --config ~/com.raywenderlich.swiftlint.yml` and tested on:**

- iPhone 15 Pro Max, iOS 17.4. (simulator)

### Related issue

- #431

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for this, @mostazomarc! I'll try to get to all the new PRs before the end of the weekend :)

**Comment by mostazomarc** [comment]
You’re welcome, @andrewtavis! No rush, take your time. Have a great weekend!

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @mostazomarc! 😊 Really appreciate all the support! Would be great to have you join a sync at some point. That's every two Saturdays, with the most recent one being today. Let me know if you'd like the details for that. It's at 14:00 UTC :)

**Comment by mostazomarc** [comment]
Thanks for the invitation @andrewtavis! I'd love to join a sync. Please share the details for the next meeting. Looking forward to it!

**Pull request merged**
