### PR TITLE
Feat: Adding colour to Placeholder prompts in Command Bar

### PR DESCRIPTION
**Pull request by SaurabhJamadagni**
- PR for the final stage of issue #35 
- Added a colorize function that returns an `NSMuttableAttributedString` to assign to the prompt in `CommandBar.swift`
- Made changes to all language keyboard interface variables to hold colored prompts that allow for checks during conditionally removing and adding the placeholder.
- Colorized prompt uses `commandBarBorderColorLight` or `commandBarBorderColorDark` depending on the appearance mode.
- Added an extension to `NSMuttableAttributedString` that allow us to color the required part of the prompt using a single function.

@andrewtavis please review these changes. This task was a big learning experience! Thanks! 😊

### CODE REVIEW

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, will take a look at this later today! Really am thrilled to provide you with the opportunity to learn from developing Scribe 😊 Will let you know how all this works!

**Comment by andrewtavis** [comment]
Noting to myself that some of the keyboard interface variables are enums, and some are classes. This should be standardized :)

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Hi @SaurabhJamadagni :) This all works really well! Really happy with the results of all this hard work of yours. My one question is why `Scribe.xcodeproj/project.pbxproj` has the changes in there. Could you explain those, or if they were by accident, could you remove them? 

Also, I noticed in [this comment](https://github.com/scribe-org/Scribe-iOS/pull/177#issuecomment-1190443922) that in interface variable files mostly we're using enums, but for `SwedishKeyboardConstants` and `SpanishKeyboardConstants` they're classes. I think the aforementioned two should be enums, so if you agree could you also standardize those? :)

Thanks again so much! Really looking forward to seeing this on my phone 😊

**Review by andrewtavis — APPROVED** [review]
Looks great! Thanks so much for the quick changes! 😊

**Comment by andrewtavis** [comment]
And no worries whatsoever on the accidental commit, @SaurabhJamadagni :) Feel free to explain your preferences on indentation, and they could be better than what I have now :)

**Comment by SaurabhJamadagni** [comment]
> Feel free to explain your preferences on indentation, and they could be better than what I have now :)

No preferences as such @andrewtavis. Xcode came with the default tab width of 4. But all the files in the codebase use a tab width of 2. So I just wanted to change my local settings to match the codebase. Forgot to revert back the changes before committing. 😅

Should I pick another issue to work on or anything specific you would like me to work on? Or do we save them for the hackathon? 😊

**Comment by SaurabhJamadagni** [comment]
> Should I pick another issue to work on or anything specific you would like me to work on? Or do we save them for the hackathon? 😊

Nevermind. I didn't see your comments on issue #35. Thank you very much for all your help :)

**Pull request merged**
