### PR TITLE
Remove corner image and icon image

### PR DESCRIPTION
**Pull request by henrikth93**
This commit will remove the corner image view and the icon image view.

### Contributor checklist

- [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [] I have tested my code with the `xcodebuild` and `swiftlint --strict` commands as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-iOS/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

- #514

### CODE REVIEW

**Comment by andrewtavis** [comment]
Tests are passing locally, so I'll take a better look at this soon :) @henrikth93: Would you be able to bring this down and do one minor edit to get the text for the Wikimedia and Scribe page a bit closer to the top like the rest of the About pages? I feel like we may have increased the distance between the top of the card and the text, and this should be reverted. The privacy policy and third party license pages have good spacing from the text to the top of the card, so maybe investigate the difference and re-apply to the Wikimedia and Scribe page?

**Comment by henrikth93** [comment]
> Tests are passing locally, so I'll take a better look at this soon :) @henrikth93: Would you be able to bring this down and do one minor edit to get the text for the Wikimedia and Scribe page a bit closer to the top like the rest of the About pages? I feel like we may have increased the distance between the top of the card and the text, and this should be reverted. The privacy policy and third party license pages have good spacing from the text to the top of the card, so maybe investigate the difference and re-apply to the Wikimedia and Scribe page?

Sure

**Comment by andrewtavis** [comment]
Thank you! We can merge this and figure out the tests later if need be, but I'll also look into it over the weekend :)

**Review by andrewtavis — APPROVED** [review]
CI errors were from an incorrect update to iPhone 16 :) The spacing was also a random `\n` at the top of the Wikimedia and Scribe page from the old formatting. Thanks for all this, @henrikth93!

**Pull request merged**
