### PR TITLE
Subtree pull Scribe-i18n

### PR DESCRIPTION
**Pull request by wkyoshida**
### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Just an example of how the workflow might look like..

- Running the following in project root to pull in changes from Scribe-i18n:
`git subtree pull --prefix Scribe/i18n git@github.com:scribe-org/Scribe-i18n.git main --squash`
- Then two commits as seen here in this PR get auto-created 

I'll look into formalizing the documentation for this over the weekend. It'll likely be best to have a generic version in the Scribe-i18n repo, but then quick repo-specific ones for each project.

P.S. Cool to see, though, that the command still appears to work despite other updates having occurred without using the command. The diff here likely appears empty, since I'd guess the manual updates to the i18n folder still matched, which is a good sign.   

### Related issue

- :globe_with_meridians:

### CODE REVIEW

**Comment by wkyoshida** [comment]
btw - attempting to run the same command again logs out the following message

```
From github.com:scribe-org/Scribe-i18n
 * branch            main       -> FETCH_HEAD
Subtree is already at commit 812482a104212e84ccb7aa620e580e9130a6581b.
```
nice

**Comment by andrewtavis** [comment]
This is one cool looking commit to branch visual :)

Screenshot_2024-08-02 23 45 51

**Comment by andrewtavis** [comment]
CC @Jag-Marcel, as this PR has some info we were discussing :)

**Comment by andrewtavis** [comment]
Nice and I was able to bring in the most recent changes in 900d068 😊

**Pull request merged**
