### PR TITLE
Add unit tests for KeyboardStyling

### PR DESCRIPTION
**Pull request by vickcoo**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
Add a unit tests for [KeyboardStyling.swift](https://github.com/scribe-org/Scribe-iOS/blob/e3ed1de13585ac74f486d48cfad72c9a2a0b9675/Keyboards/KeyboardsBase/KeyboardStyling.swift).

### Related issue

- #8

### CODE REVIEW

**Comment by vickcoo** [comment]
Hi @andrewtavis, I need your review 🤳🏻

**Comment by andrewtavis** [comment]
Do you want to do a first review of this, @fabulouiOS-monk? :) Happy to check it before or after 😊

**Comment by fabulouiOS-monk** [comment]
I think I have reviewed from my side, there are some typos in method name. But I am finished with my review. Thanks @andrewtavis.

**Comment by andrewtavis** [comment]
I'll check and fix the names in my review then, @fabulouiOS-monk :) Thanks so much!

**Review by andrewtavis — APPROVED** [review]
Thanks for all of these, @vickcoo! Really great to be making so much progress with testing already! Let us know in the issue what you'd think would be the next best thing to work on 😊

**Comment by vickcoo** [comment]
Hi @andrewtavis, I'll be work on the [KeyboardKeys](https://github.com/scribe-org/Scribe-iOS/blob/25219788b47fb8db2b63907251633f87eff573e0/Keyboards/KeyboardsBase/KeyboardKeys.swift) as the next tests!

**Comment by andrewtavis** [comment]
Nice, @vickcoo! Looking for are to the tests! :)

**Pull request merged**
