### PR TITLE
System to pick a translation language for each keyboard

### PR DESCRIPTION
**Pull request by Jag-Marcel**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR creates a menu for each keyboard, where you can choose a language to be used for Scribe's translation feature. Previously, every keyboard would require English as the translation language.

### Related issues

- #255 
- #307 
- #469 
- #470 

### Blocked by

- #458
  - This PR needs to have the translation tables for it to support different translation languages
  - Currently, I chose `[language abbreviation]_translations` as the name for the tables, but could still be changed
- scribe-org/Scribe-Data#70
  - This also blocks #458, since it needs these tables to exist

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for the detailed PR and fixing the merge conflicts, @Jag-Marcel!

**Comment by andrewtavis** [comment]
Brought in the localizations to main so that we can get v3.1 out, @Jag-Marcel 😊 Would be great if we can get a "Follow us on Mastodon" localization key in! I'll bring in everything else and send along v3.1 now though as I'd like to get it out today. No stress on one menu option not being fully localized :)

**Comment by andrewtavis** [comment]
@Jag-Marcel, the most recent commit adds in a table for each language with a `word` column and then ISO-2 code columns for each of the respective translation columns for the given language. There are a ton of weird conflicts here now... Let me know if you have thoughts on this would would like me to dive deeper into then! Generally I'd say we're keeping the `.sqlite` files that are in the branch and then we can update them again with the new data once I've ran all of the translation scripts. We should likely get rid of the changes to `Scribe.xcodeproj/project.pbxproj` and reimplement anything that's here as the changes to add in the English keyboard are likely more involved than the changes for the branch. I'm not sure on `Keyboards/KeyboardsBase/Utilities.swift`, but this is likely just some simple conflicts that can be resolved in the editor 😊 Happy to do a call to look into this!

**Comment by Jag-Marcel** [comment]
Should be done as soon as we have the full tables now!

**Comment by andrewtavis** [comment]
Nice, @Jag-Marcel! This is amazing stuff here :) I'll do a review as soon as I can. Let me know if there's anything else you'd have interest in looking into over the last week 😊

**Comment by andrewtavis** [comment]
@Jag-Marcel, playing around with it a bit, and let me just say that you really have a knack for user experience :) My thought was always that the user would select a new radio button and then go back to the settings via the back button, but then given the UI they will see the change in the interface option, so it makes total sense that we take them back directly. As with the commands on highlighted words, well done 👏

**Comment by andrewtavis** [comment]
We do have some keyboard key spacing issues that are just the damn conditionals for language getting mixed as always. Might be something that we should consider setting up an enum for at some point, but as you can see there's a space being applied after the `L` that's bringing all the keys in to close with the gap to `Ñ`:

Simulator Screenshot - iPhone 15 Pro Max - 2024-08-19 at 20 21 35

This is the German keyboard with Spanish translation language :)

Padding code in general starts [here](https://github.com/scribe-org/Scribe-iOS/blob/39d35d65258aa35c5ccf5de54f925861b33754e7/Keyboards/KeyboardsBase/KeyboardViewController.swift#L1706). 

For the German keyboard there are spacing issues for:
- French (padding issues)
- Russian (see image below)
- Spanish (padding issues)
- Swedish (padding issues)

Simulator Screenshot - iPhone 15 Pro Max - 2024-08-19 at 20 26 51

The issue above is more key size than padding, which is in [KeyboardKeys.swift#L212](https://github.com/scribe-org/Scribe-iOS/blob/39d35d65258aa35c5ccf5de54f925861b33754e7/Keyboards/KeyboardsBase/KeyboardKeys.swift#L212). Might need to check these sorts of things for iPads as well.

Any thoughts on this? An enum would be ideal, or maybe a variable for the translation language itself so that we're not checking between what the keyboard language is and whether translation is in use (not what the translation language actually is).

**Comment by andrewtavis** [comment]
I'm also a bit confused on the order of the translations. When I'm translating from Spanish -> German I'd expect to be able to do `Brasil` (a `word` that we did transfer that's in `ESLanguageData`) to Brasilien (the `de` key), but I'm getting `Nicht in Wikidata` like it's not a key. Are we using `DELanguageData` for this? I don't get `Nicht in Wikidata` for trying to translate `00` that's a `word` in `DELanguageData` which returns back `00` as it is in its `en` key, but then this should not be found in this case as it's not in `ESLanguageData`.

Ah I see what might be going on here (pardon the stream of conscious). We have it setup where it's from `es` in `DELanguageData` to `word`? It should be from `word` in `ESLanguageData` to `de` :) Reason for this is that we want there to be a unique result for any word that we'd return. In the machine translation process there are multiple words that might have been/might be translated to the same word, and then if we go from `es` to `word` in `DELanguageData` we'd then have multiple `word` options to choose from. Thinking of the Spanish word for over, `sobre`. As of now we've had `'nüber` translate to it, and we can assume that `über` will to, but we wouldn't want to return the former. We want to translate `sobre` to `über`, have `sobre` be the word and `über` be the `de` key, and then have a unique result for each word that we're translating :)

Let me know if this makes sense! Hope I'm understanding what I'm seeing from the translation results :) Will look into the code a bit more later.

**Comment by Jag-Marcel** [comment]
I'll look into the first issue, maybe a function that returns the controller language's translation language is good? That could also simplify other places where it's used.
I'll change the way the translation tables are used so it works as intended as well.

**Comment by Jag-Marcel** [comment]
> maybe a function that returns the controller language's translation language is good?

Turns out that function already exists, I just forgot I made it at some point 🙃

**Comment by andrewtavis** [comment]
Looking forward to the changes, @Jag-Marcel! :)

**Comment by andrewtavis** [comment]
Hmmmm, ya this could prove to be a problem. Maybe the structure of the database is off? I understand your original inclination on this to use one DB for the whole thing rather than go across multiple, which also makes sense given downloading data in the future. As I'm thinking, we'd now need to bring down the `ESLanguageData` DB to translate to German, which is a bit weird, but I guess does make sense in so far as if the user has say German and French, then they'd just have the `ESLanguageData` for both :)

I'll take a look at this later!

How are we on the layouts?

Thanks for all the efforts, @Jag-Marcel!

**Comment by Jag-Marcel** [comment]
The layouts should be done, I'll try looking into the DBs some more as well.
Maybe they don't get initialized quick enough for data to be read because of some async processes? We could also try putting translations for all languages in one separate database file

**Comment by andrewtavis** [comment]
That's a thought as well, @Jag-Marcel! Could be something in the language keyboards base where we have all the tables in one names after their source language or something like that. If we can't figure out the current implementation, then I can rework the process :)

**Comment by andrewtavis** [comment]
Very sorry for the wait on all this, @Jag-Marcel! Thanks so much for your patience :) d4e2b0a sends along new language DBs without a translation table, and then there's a common `TranslationData.sqlite` DB that we can now use for translation. This will be consistent even post Outreachy, and we won't need to worry about a single language DB being assigned anymore.

How do you want to proceed here? Would you want to finalize the new process via the SQLite access of the new `TranslateData.sqlite` DB? Anything I can do to support?

**Comment by Jag-Marcel** [comment]
@andrewtavis I'll look into this and tell you if I need anything, glad that the process and everything is finally figured out!

**Comment by andrewtavis** [comment]
Ok we're good to go with the `.xcstrings` file, @Jag-Marcel 😊 I guess that I just didn't have Korean locally, which is what came down with the `git pull --rebase --autostash` :) See you tomorrow!

**Comment by Jag-Marcel** [comment]
The localization not working was because we still had the old string keys in iOS, but I also had to disable the indents in the third party licenses for now because of the way we generated them. Could probably be reactivated in a future issue but do we even want to have them? I think the lists there looks fine even without indents.
Also we probably want to find a way to detect links in texts like the privacy policy and licenses. I refactored the way we add them here so we only need to add each link to a list once, but ideally we should have a way to find them from specific texts automatically.

**Comment by andrewtavis** [comment]
Ah totally true, @Jag-Marcel! This PR then also closes #503 🚀 Thank you!

**Review by andrewtavis — APPROVED** [review]
So happy to have this merged, @Jag-Marcel! Thanks so much for the hard work and determination to see this through to the end 😊 The implementation exceeds expectations given its everything we were looking for + your improvements to the user flow with the language being selected directly. Such an amazing step towards making Scribe an accessible application to language learners from all over the world 🌐

**Pull request merged**
