### PR TITLE
Add German Language Support

### PR DESCRIPTION
**Pull request by gitpushOmnik**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have updated the [CHANGELOG](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md) with a description of my changes for the upcoming release (if necessary) 

---

### Description

This PR introduces changes to the add German Language Support for the application. The language of the privacy policy, keyboard installation and community texts according to the user's system set language. 

The language changes according to the system set language. The default language is English.  

Adding support only for German Language. Will add other languages later once this PR gets approved. Need feedback on the format.

The language is currently translated into German. The texts and descriptions can be changed later to include a more grammatically correct version.

### Related issue

#ISSUE_NUMBER
PR for issue #120

### CODE REVIEW

**Comment by gitpushOmnik** [comment]
Sorry about that @andrewtavis Didn't notice my changes were behind the main commit done recently. I have pulled the request on a separate branch though.

**Comment by andrewtavis** [comment]
Thanks for this, @gitpushOmnik! I can handle the merge conflict in a bit 😊 I changed the way that we're doing the privacy policy as I realized that the hyper link assignment within `setENPrivacyPolicy` is going to be consistent regardless of the languages :) It's now just `setPrivacyPolicy` and takes arguments based on the language, which will be easy to integrate. I can also give the German privacy policy a read through to do some fixes 🤓

**Comment by gitpushOmnik** [comment]
Okay. Once you review the conflicts and merge the pull requests, I can then start adding support to different languages that conforms to the newly updated format for displaying the policies that you make with this PR.

**Comment by andrewtavis** [comment]
Great, thanks @gitpushOmnik!

**Comment by gitpushOmnik** [comment]
Sounds good!

**Review by andrewtavis — APPROVED** [review]
Thank you, @gitpushOmnik! Looks really great, and very happy to have be able to open up Scribe to all the contributions that come with localizing the app 😊 I'm going to bring this in and work on it a bit myself as there are lots of little formatting things that are going on now given the differences between German and English (specifically word lengths....... 😅). 

Will update you in the issue when it's all finished :) :) For now I'd say let's hold off on other languages as we're going to be changing the app screen so dramatically during the coming months, so it'll be lots that needs to be rewritten as we can't release before #96 is finished anyway.

Thanks again so much! 🚀

**Comment by gitpushOmnik** [comment]
Of course. We can work together later in the future on this localization feature for adding support to different languages after the app screen is made final. Happy to work on this and thank you so much for merging the pull request :)

**Comment by andrewtavis** [comment]
Thank you so much for the PR! 😊 Happy to work on these things with you later :)

**Pull request merged**
