### PR TITLE
Including a pronouns to tense dictionary for French

### PR DESCRIPTION
**Pull request by SaurabhJamadagni**
- PR for sub task of issue #208 
- Added a dictionary in french interface variables.

@andrewtavis could you please review these changes. Also, maybe confirm that the dictionary is correct. I created it using as much I could understand about French pronouns from an article 😅

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
All looks good, @SaurabhJamadagni! 😊 Changes requested, as don't we need to add a check into `getPronounAutosuggestions` to see if it is a verb first, and if not just return the word? `ne` - French for `not` - won't be conjugated, so we just want this word returned :)

**Comment by andrewtavis** [comment]
The above commits also fixed the super minor issues with the French files :) Thanks for working with the language files like this! 🚀

**Comment by SaurabhJamadagni** [comment]
@andrewtavis ce4b7b6 should fix it. As the `verbs` JSON returns an optional, I think it should do it. If no value is found, it by defualt returns the verb itself. Will this do?

**Review by andrewtavis — APPROVED** [review]
Fixes are perfect, @SaurabhJamadagni! Thanks for the work on this :) :) We can do a similar bit for Spanish for the words listed in the issue, and then we're done with this 🚀

**Pull request merged**
