### PR TITLE
Added version to ui along with releases github page link

### PR DESCRIPTION
**Pull request by Mehul721**
#504 Version needs to be converted to an external link to directs towards the releases on GitHub 

- [x] This pull request is on a [feat/feedback-and-support] and not the main branch

### CODE REVIEW

**Comment by andrewtavis** [comment]
Looks like there are [some errors](https://github.com/scribe-org/Scribe-iOS/actions/runs/11096072965/job/30825641031?pr=505) with the build here :)

```
xcodebuild: error: Could not resolve package dependencies:
  package 'grdb.swift' @ dc03b8a29e2f5d51bd41e0971bba9a9975a29934 is using Swift tools version 6.0.0 but the installed version is 5.10.0 in https://github.com/groue/GRDB.swift.git

package 'grdb.swift' @ dc03b8a29e2f5d51bd41e0971bba9a9975a29934 is using Swift tools version 6.0.0 but the installed version is 5.10.0 in https://github.com/groue/GRDB.swift.git
```

Let us know if you have any thoughts on how to fix this, @Mehul721! Happy to support if you need assistance with them :)

**Comment by andrewtavis** [comment]
Hmmm, yes I'm realizing just now that there's been a major version update. Maybe the thing to do is for this we can set the tests to Swift 5.10.0 and then update to Swift 6.0.0 in a new issue 🤔 Pinging @fabulouiOS-monk for a quick opinion here, if you have a moment :)

**Comment by fabulouiOS-monk** [comment]
There are two ways: 1. to make use of 6.0 in the github action file.
2. To downgrade the GRDB swift version (which I think is a hassle)

Let's try with the 1st way: @Mehul721  can you please attach the following to pr_ci.yml file:
 - name: Install Swift 6.0.0
        uses: fwal/setup-swift@v1
        with:
          swift-version: '6.0.0' 
          
          
    Note: You will find the pr_ci.yml file in hidden folder `**.github > workflows> pr_ci.yaml**`

**Comment by Mehul721** [comment]
> * name: Install Swift 6.0.0
>   uses: fwal/setup-swift@v1
>   with:
>   swift-version: '6.0.0'

Hi so I have just updated the pr_ci.yml file.Kindly have a look.

**Comment by andrewtavis** [comment]
Did you push the changes, @Mehul721? I'm seeing just one commit on this PR still :)

**Comment by Mehul721** [comment]
I created a new PR for that.Still please let me know in case of an issue.

**Comment by fabulouiOS-monk** [comment]
@Mehul721 can you please share the PR link?

**Comment by fabulouiOS-monk** [comment]
> @Mehul721 can you please share the PR link?

Got it!

**Review by andrewtavis — APPROVED** [review]
Sorry for the wait on this, @Mehul721 :) Has been a crazy last month and a half for me and I really needed to focus on the data project here for [Outreachy](https://www.outreachy.org/). I made a minor change to pin GRDB to 6.0..<7.0, which did allow the CI to pass and all's working on an emulator. Solution isn't perfect, but we can figure it out later.

Appreciate the efforts and hope you contribute again! Promise the next one won't take this long! :)

**Pull request merged**
