### PR TITLE
Enter selected text into Scribe

### PR DESCRIPTION
**Pull request by Jag-Marcel**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

These are changes to the behaviour of the Scribe key when text in the text field is selected. Currently, it only shows you annotations for the selected word (i.e. "N" for neuter words). Here, I changed it so the selected Scribe command's action is executed on the highlighted text.
#### Before
Screenshot 2024-08-03 at 12 48 26

#### After (after pressing "Plural" in the command bar)
image

We also considered an option where the text would simply be entered into the command bar's text field, but decided against it:
Screenshot 2024-08-03 at 13 04 27

### Related issues

- #141

### CODE REVIEW

**Comment by andrewtavis** [comment]
A few things to consider here, @Jag-Marcel:

- What happens if the word isn't the last one in the proxy?
  - Do we replace the word where the other one is
- We also need to make sure that we're not including a space at the end of such commands that might cause an inadvertent double space for the user
  - Maybe we can check to see if there is a space after the word already so that we only add a space if there isn't one already 🤔

This is amazing! Thank you! 🚀

**Comment by andrewtavis** [comment]
Talking about it in the sync: The general thinking is that the command should be directly ran :)

**Comment by andrewtavis** [comment]
This is ready for a file review at this point, right @Jag-Marcel? :)

**Comment by Jag-Marcel** [comment]
> This is ready for a file review at this point, right @Jag-Marcel? :)

Not yet, I still haven't changed the behaviour

**Review by andrewtavis — APPROVED** [review]
Really amazing work here, @Jag-Marcel! 😊 Thanks so much for putting so much care into this issue! Really has turned out wonderfully, and using it even in testing was really fun :D

**Pull request merged**
