### PR TITLE
Create GitHub actions workflow to run ci process 499

### PR DESCRIPTION
**Pull request by fabulouiOS-monk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Added .yaml file for running unit test in github workflow.

### Related issue

- #499

### CODE REVIEW

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, The test pipeline is now working fine. But It's taking 8 mins to build and run. Need to see what we can do.

**Comment by andrewtavis** [comment]
How are you feeling about it at this point, @fabulouiOS-monk? :)

**Review by andrewtavis — APPROVED** [review]
#500! Fitting that it's you sending it along, @fabulouiOS-monk, and also that it's such a major step for Scribe-iOS 😊 Really appreciate your dedication to the project!

Thanks also @vickcoo for the tests here! Really off to a great start!

**Comment by andrewtavis** [comment]
Note also that org naming conventions are we name the workflows after the file, but we can talk about this if we would like to give them a title rather than the file :)

**Pull request merged**
