### PR TITLE
Fix some RU localization issues #221

### PR DESCRIPTION
**Pull request by japanese-goblinn**

### CODE REVIEW

**Comment by japanese-goblinn** [comment]
@andrewtavis well I'm not sure about changes in `RUInterfaceVariables.swift` due to layout issues 
image

**Comment by japanese-goblinn** [comment]
@andrewtavis is it possible to make this commands scrollable? If not - reducing font size should be find, but I find this more like a patch than really solving the problem

**Comment by andrewtavis** [comment]
We'll definitely need to figure out a way to allow the buttons to scroll later, but with all that's going on for autosuggest and the UI for v2.0 it's definitely not a priority. I wrote some ideas for it a long time ago in #37. For now, if the "abbreviation" for plural doesn't work, then we'll just need to patch it and make the text smaller in this case only.

**Comment by andrewtavis** [comment]
And checking the pronoun changes with you:

Is `Винительное местоимение` plural or singular? I put it in to check and it said "Accusative pronoun". What I want this to say is "Accusative pronouns", so each of them should be in the plural form so that it's "select from the pronouns". Check checking 😊

**Comment by andrewtavis** [comment]
And just checking my understanding: `Множ` is more like the word `Multiple`?

**Comment by japanese-goblinn** [comment]
> 

oh, plural for is different. i'll fix it

**Comment by japanese-goblinn** [comment]
> And checking the pronoun changes with you:
> 
> Is `Винительное местоимение` plural or singular? I put it in to check and it said "Accusative pronoun". What I want this to say is "Accusative pronouns", so each of them should be in the plural form so that it's "select from the pronouns". Just checking 😊

Oh, plural form is different actually. I'll fix it

**Comment by japanese-goblinn** [comment]
> And just checking my understanding: `Множ` is more like the word `Multiple`?

No, it's more like if you truncate the word end. So `Множ` more like `Mult` and `Множественное` is `Multiple`

**Comment by japanese-goblinn** [comment]
Now I see that adding font adjustment for this label may be a simple solution for the problem. Until scrolling will be implemented

**Comment by andrewtavis** [comment]
> Oh, plural form is different actually. I'll fix it

Thank you! Very much appreciated 😊

**Comment by andrewtavis** [comment]
> Now I see that adding font adjustment for this label may be a simple solution for the problem. Until scrolling will be implemented

Also something to consider, depending on how much smaller we'd need to make the font. I think that changing the word makes sense, and I can play with the settings a bit on my end :)

**Comment by japanese-goblinn** [comment]
> > Now I see that adding font adjustment for this label may be a simple solution for the problem. Until scrolling will be implemented
> 
> Also something to consider, depending on how much smaller we'd need to make the font. I think that changing the word makes sense, and I can play with the settings a bit on my end :)

I'll take a look on that and play with `minimumScaleFactor` a bit. I'll let you now

**Comment by japanese-goblinn** [comment]
@andrewtavis Well I was not happy with font adjusting so I decided to use short version of the word. Not perfect but better than `Множ.`

image

image

**Review by andrewtavis — APPROVED** [review]
> Well I was not happy with font adjusting so I decided to use short version of the word. Not perfect but better than Множ.

Ya this all makes sense. Making the font of all the words smaller would also be a bit weird. I feel like this works for now, and we can maybe work to expand it later. Regardless, good to have the "Already plural" message fixed, as well as the pronoun labels! Thank you! 😊

**Pull request merged**
