### PR TITLE
Adding a greeting bot Workflow through github actions

### PR DESCRIPTION
**Pull request by RishiKumarRay**

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
I did some research on this to figure out what all of this means :)

Thanks for doing `actions/first-interaction@v1` and not `actions/checkout@v1`! I like that this is going to be something that's talking to new contributors and won't be sending me messages each time I open an issue 😋 

Can you rename it `welcome.yml` and switch the `name` to `Welcome` as that's a bit more descriptive of what's going on? I was confused with greetings and thought it was gonna be like an `actions/checkout@v1` bot.

As far as the messages are concerned, I have some ideas of how to add formatting to them and make them a bit more personal. I'll merge with the above changes to make sure you maintain credit for this, and then will send along my edits. We can then discuss them in the #111, as I'm curious what your feedback will be :)

Thanks for this!

**Review by andrewtavis — COMMENTED** [review]
Sending along an approval for the sake of the review ;)

**Comment by RishiKumarRay** [comment]
@andrewtavis approval for what? :)

**Comment by andrewtavis** [comment]
@RishiKumarRay, never mind this. I realized I hadn't actually reviewed it, but then I can't review after it's already merged anyway :)

**Pull request merged**
