### PR TITLE
Add app hints to convey instruction information 329

### PR DESCRIPTION
**Pull request by fabulouiOS-monk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

- #329

### CODE REVIEW

**Comment by fabulouiOS-monk** [comment]
Hey @andrewtavis, I had to make some changes in **KeyboardViewController.swift**, to fix swiftLint issues. I don't know how it was merged in the first place to the main.

**Comment by andrewtavis** [comment]
Nice, @fabulouiOS-monk! Super great 😊 And just in time for the v3.0 release! 

Not sure how the SwiftLint errors got in either 🤔 The checks are only running on PRs, I think, so likely just me adding them in via commits 😅 Thanks for fixing them!

I'll check this later this evening :)

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, One more thing, I have only added it to the AboutViewController, We need to add it to other places wherever needed, similar to what we did here. 😃

**Comment by andrewtavis** [comment]
Nice, @fabulouiOS-monk :) Sounds doable! Do we have the reset app hints option in the menu already? Haven't been able to bring it down locally 😊

**Comment by fabulouiOS-monk** [comment]
No @andrewtavis, in the current push we don't have the reset app hints option. Every time the user will visit to that screen, we will show that TipCard.

**Comment by andrewtavis** [comment]
Ah ok, but let's definitely add this option in then and have some external variable that gets reset by the menu option being clicked :) 

Really exciting progress here! Such a nice feature to round out the application 😊

**Comment by fabulouiOS-monk** [comment]
@andrewtavis  ^^, for reference above comment.

**Comment by andrewtavis** [comment]
Hey @fabulouiOS-monk 👋 1ee3a6c sends along some styling and functionality edits. Big thing is that we need three different ones such that when the user closes one, they all don't close. That's now been added, and generally I think it's progress, but we have a major bug where the tooltip is behind the header and thus can't be clicked. You had them lower than where they'd naturally be right at the top of the page, butt hen when it's moved up it's obscured by the title text and can't be clicked (I'm assuming this is because the view of the page title is blocking it).

Do you want to bring the most recent changes down and see if you can bring the tooltips forward? Screenshots below:

Working fine:

simulator_screenshot_C0743E4C-2142-4368-BE57-ED6AADAEBE5C

And these two aren't:

simulator_screenshot_6851AF09-86A0-423F-A845-6A7F9F80FE0D

simulator_screenshot_88FE4870-2410-428D-91A9-EEB2C5A7818F

Let me know if you have any thoughts!

**Comment by andrewtavis** [comment]
Also, just another quick note of something it would be cool to fix: On the About tab the distance between "About" and "Community" is less than the distance between "Settings" and "App settings" 🤔 Maybe we could move the table view with "App settings" up a bit so the distance to "Settings" is the same as the counterparts on the About page?

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, I tried with a few things to bring the tipCardView to the front but it doesn't work. One way I can think about is creating a UIView which will present on top of the TableView and in that transparent UIView we can show the tipCardView. Any other way you can think of?

**Comment by andrewtavis** [comment]
Ya I was working at it for a bit as well before deciding to check in, @fabulouiOS-monk :) I think your idea of the UIView over the whole TableView is a good one! Let's give that a try, and if it doesn't work let me know and we can go back to the drawing board/ask the community 😊

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, I tried applying the above idea, half of it works, but when resetting the value through the AboutViewController sections it does not update the `settingsTipCardState` hence UI breaks.

**Comment by andrewtavis** [comment]
Do you want to send along the most recent changes and I'll take a look, @fabulouiOS-monk? :)

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, Yeah sure, I push the changes. It only helps to show the tipCard initially at the top of the table view. but the presentation doesn't work correctly.

**Comment by andrewtavis** [comment]
Hmmmmm, ya this is a tough one as it basically disappears and you can't bring it back, and then for me it also gets added above the install one such that you have two tooltip cards at once. Could we try adding it to the storyboard such that it's above the other parts, @fabulouiOS-monk? So we have a View that's above the headers for each of the pages in question, and then we link it to a variable and add in the tooltips onto those. That way we start from their position on top of everything, and then we build from there?

If the above sounds ok, then maybe we should revert the most recent commit and start from the last one?

We'll get this!

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, Finally the above issue is solved 😄 . It was such a simple solution, instead of **view**, we needed to use the **navigationController.navigationBar**, since we want to show our tipCardView on top of the navigationBar and not the view. 

Took so many hits and tries 😅 . Congratulations!!

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, I wanted to join previous one too, but well god(my current organisation 😉) has different plans. I will try to join if no sudden plans are made.

**Review by andrewtavis — APPROVED** [review]
Amazing that this all got worked out, @fabulouiOS-monk! Really wonderful stuff here 😊 Looking forward to expanding these later when the menu has more options! 🥳

**Pull request merged**
