### PR TITLE
Fixed "isCapitalized" typo

### PR DESCRIPTION
**Pull request by helloITdepartment**

### CODE REVIEW

**Review by andrewtavis — APPROVED** [review]
Hey there @helloITdepartment! Thanks a lot for finding this for us 😊 Unsure if you're participating in `Hacktoberfest`, but I'll mark this with the label and maybe you can get some credit for it :)

**Comment by helloITdepartment** [comment]
Thank you, I am!
I noticed it while working on issue #34, which I think I may nearly have solved, there just seems to be a weird bug when drawing the keys and I'm trying to track down where that all happens so I can solve it

**Comment by andrewtavis** [comment]
Looking forward to that PR, @helloITdepartment! Let me know in the issue if I can support in any way 😊

**Comment by helloITdepartment** [comment]
A bit silly, but I was wondering how exactly to assign the issue to myself 😅

**Comment by andrewtavis** [comment]
Not silly at all! You need to comment in the issue, and then I can assign it to you :)

**Pull request merged**
