### PR TITLE
Switch case from conditional statement to determine keyboard width

### PR DESCRIPTION
**Pull request by mcrkgus**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have tested my code with the `xcodebuild` and `swiftlint --strict` commands as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-iOS/blob/main/CONTRIBUTING.md#testing)

---

### Description
 Switch from conditional statements to switch and case statements to determine the keyboard width.

 ``` swift
switch key {
      case "ABC", "АБВ":
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * 1).isActive = true
     case "#+=", "selectKeyboard":
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarSpecialKeysWidth).isActive = true
      case "delete":
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarDeleteKeyWidth).isActive = true
      case SpecialKeys.capsLock:
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarCapsLockKeyWidth).isActive = true
      case SpecialKeys.indent:
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarIndentKeyWidth).isActive = true
      case "shift" where idx == 0:
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarShiftKeyWidth).isActive = true
      case "shift" where idx > 0:
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarRightShiftKeyWidth).isActive = true
      case "return":
        layer.setValue(true, forKey: "isSpecial")
        widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarReturnKeyWidth).isActive = true
      case "123", ".?123", "return", "hideKeyboard":
        if DeviceType.isPad
            && key == "return"
            && ((commandState != .translate && ["English", "Portuguese", "Italian"].contains(controllerLanguage)) ||
                (commandState == .translate && ["en", "pt", "it"].contains(getControllerTranslateLangCode())))
            && row == 1 {
          layer.setValue(true, forKey: "isSpecial")
          widthAnchor.constraint(equalToConstant: numSymKeyWidth * 1.5).isActive = true
        } else {
          layer.setValue(true, forKey: "isSpecial")
          widthAnchor.constraint(equalToConstant: numSymKeyWidth * 1).isActive = true
        }
}
```

### Related issue

- #525

### CODE REVIEW

**Comment by mcrkgus** [comment]
@andrewtavis 
I have revised and reflected the parts you mentioned! Please check. Thank you 😊

**Comment by andrewtavis** [comment]
Fantastic, @mcrkgus! I'm for a few days till the 26th, so I won't be able to do a final review until then. @Jag-Marcel, if you have a moment, would you be able to take a look at this? If you're ok with it I can then merge, or feel free to `+1` and I'll finalize it when I'm back :) 

@mcrkgus, from here you'd be welcome to continue any further work for #399 and #525. What are the next steps you're planning?

**Comment by Jag-Marcel** [comment]
I'll take a look tomorrow morning 👍

**Review by Jag-Marcel — APPROVED** [review]
All looks good to me, works fine on all keyboards still and this is much simpler and easier to read, good job @mcrkgus!
@andrewtavis I think this is good to be merged

**Comment by Jag-Marcel** [comment]
@andrewtavis On a more unrelated note, I noticed that on iPad, the key width in landscape is all over the place. If you start a keyboard on landscape, the keys change width slightly when switching from letter keys to symbols. If you start on portrait, all special keys remain weirdly thin in landscape, the regular keys start out normal albeit with more space between them, but when you switch to symbols they are really thin.
This doesn't have anything to do with the changes in this PR I think, it's also a problem on the main branch.

Is there already an issue for this that I missed, or do you want me to make one?

**Comment by andrewtavis** [comment]
There's no issue for this so far, @Jag-Marcel :) Would be great if you made one and included some screenshots.

**Review by andrewtavis — APPROVED** [review]
Thanks for the great first contribution, @mcrkgus! Hope we can get another PR from you again soon :) Please let us know what the next steps are for the issues you're working on 😊

**Pull request merged**
