### PR TITLE
Privacy policy text in About section

### PR DESCRIPTION
**Pull request by SaurabhJamadagni**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This pull request add the Privacy policy content in the About section tab. It also cleans up the installation screen. Previously the installation screen had the privacy policy and link to GitHub. Both have been removed as they have their own section in the About page now.

Current Installation screen only shows the installation instructions along with the logo. More content to be added with further issues. @andrewtavis, I removed the community section from the installation screen as well along with the privacy policy as it was repeated too. Hope that's okay.

Tested UI on:
- iPhone 14 Pro
- iPad Pro 11"
- iPhone SE (3rd gen)

### Related issue

- #317

### CODE REVIEW

**Comment by SaurabhJamadagni** [comment]
Commit 9fd6b365522ac70f1a0a5f19f317e5f78750ba8e adds the subject to the email like discussed in the previous PR (#328) 😄

**Comment by SaurabhJamadagni** [comment]
Also just a small git question. Right now I pushed my changes to create a PR. GitHub then alerted me that there was a merge conflict. I resolved it using the web editor provided by GitHub to resolve the conflict. How can I pull the conflict to my machine to resolve it in Xcode and then push the commit? Any idea @andrewtavis or @wkyoshida? 😅

**Comment by andrewtavis** [comment]
> @andrewtavis, I removed the community section from the installation screen as well along with the privacy policy as it was repeated too. Hope that's okay.

This makes sense! Thank you, @SaurabhJamadagni!

> How can I pull the conflict to my machine to resolve it in Xcode and then push the commit? Any idea @andrewtavis or @wkyoshida? 😅

I personally wouldn't use Xcode for this, as they don't have terminal support anyway. For all things Git for Scribe I use VS Code. That's also where I have the [swift-formatter](https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-swiftformat) that I've been using to format files on autosave and clean them up from time to time :) I'll look for some resources for this and write something up 🙃

**Comment by SaurabhJamadagni** [comment]
> I personally wouldn't use Xcode for this, as they don't have terminal support anyway. For all things Git for Scribe I use VS Code.

No no, I meant how do I see the conflict in Xcode. I will be using git through the terminal itself. But when there is a merge conflict, the code gets the `<<<<<` pointers in the code right. In today's case, I had a merge conflict on GitHub but I couldn't see it in my code. Does that make sense? 😅

**Comment by andrewtavis** [comment]
Ah I guess you could see the conflict in Xcode as well when you rebase. Sorry I just turn my brain off for anything Git related with Xcode…

**Comment by andrewtavis** [comment]
Let me look into it, and maybe you and I can do a session where we play around with a PR a bit :)

**Comment by wkyoshida** [comment]
@SaurabhJamadagni 
Is this more or less what you were wondering?
https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts

If you `pull` down the latest `main` and try to `merge` locally, I believe `git` would let you know of merge conflicts. I'd say it's totally fine to play around in your local! Experiment to better understand how `git` works - so long as (rule of thumb) avoiding `push --force` or alike. If local gets messed up, can always pull down what's in GitHub to reset your local.

---
Maybe relevant too?
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by SaurabhJamadagni** [comment]
> Let me look into it, and maybe you and I can do a session where we play around with a PR a bit :)

Ahh sounds good @andrewtavis. Thanks!

> Experiment to better understand how git works - so long as (rule of thumb) avoiding push --force or alike.

Thanks for the resources @wkyoshida! Definitely never force pushing.

> Maybe relevant too?

Yeah this seems more useful. I do get confused as to what exactly happens on a rebase. Most of the conflicts arise before pushing to remote so this should be useful! Thanks a lot 😄

**Review by andrewtavis — APPROVED** [review]
Working really well, @SaurabhJamadagni! Will merge, but a few minor observations:

- The yellow corner for the installation steps seems to be a bit too large
- The text for the privacy policy is cut off by the corner triangle (this is why the `/n` was there, but maybe we can just wrap the text so it doesn't start beneath the corner)
- We can discuss this in the daily, but it makes sense to me that navigating to a nav bar tab would always go to the base screen for that part of the menu

Such great progress! 👏😊 We're really getting there! 🚀

**Pull request merged**
