### PR TITLE
Added external link icon in "About" page (#393)

### PR DESCRIPTION
**Pull request by Jag-Marcel**
- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This adds an icon to show that several buttons in the "About" page in the app link to external sites, mainly the ones outlined in the issue #393, with the exception of the "Share" button, which doesn't necessarily link to outside the app. I also thought that the "Share" icon was already universal enough for people to interpret what the button does at a glance.

I used the icon that was used as an example in the original issue, but it can be replaced by similar ones that might fit the style of the rest of icons better if there is a need. 

I tested by using the Xcode iPhone 15 Pro, Pro Max and iPad Pro 11in simulators

### Related issue

- #393

### CODE REVIEW

**Comment by andrewtavis** [comment]
Generally everything's looking great here, @Jag-Marcel :) One thing to note is that the resolution of the icon isn't scaling particularly well. I guess I'd also prefer if the arrow was going right out at 45 degrees rather than say 55. Would something like [this icon](https://icons8.com/icon/set/external-link/ios-glyphs) be possible. The other thought I'm having on this is also that the icon would ideally be grey like the chevrons that indicate navigating within the app.

Let me know if you'd like to work on the above two points! Thanks for the work till now 😊

**Comment by andrewtavis** [comment]
I realized that designs were missing for this, @Jag-Marcel :) I did some minor edits for it just now, which can be seen on Figma here: https://www.figma.com/file/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?type=design&node-id=513%3A2206&mode=design&t=ReaZQG3S33ML5O2k-1.

**Comment by Jag-Marcel** [comment]
Alright, I'll get to it. Should be a fairly simple change.

**Comment by andrewtavis** [comment]
Nice @Jag-Marcel, thanks for looking into this further 😊

**Review by andrewtavis — APPROVED** [review]
This is really great for the first contribution, @Jag-Marcel 😊 Appreciate the quick turn around in addressing the comments. Would be great to work with you on another issue!

Will bring this in and do some minor edits I'm seeing that are unrelated before closing the issue :)

**Pull request merged**
