### PR TITLE
Dark mode changes for app screen

### PR DESCRIPTION
**Pull request by SaurabhJamadagni**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
- [x] I have updated the [CHANGELOG](https://github.com/scribe-org/Scribe-iOS/blob/main/CHANGELOG.md) with a description of my changes for the upcoming release (if necessary) 

---

### Description

- This PR introduces changes to the color sets in the assets directory.
- Had to change the `GitHubCorner` image as the previous one had a white corner that was extending into the text when switched to dark mode.
- Tried using already existing color variables instead of creating new ones with the exact same color just different labels 😅 

### Related issue

- PR for issue #260

### CODE REVIEW

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, sorry about the numerous commits. I just can't get this one merge conflict to be resolved. 

image

This one conflict is causing a problem. We don't want the `.light` to be there. So when I take it away in my code the conflict is resolved, but adding the change again as it is needed for the dynamic dark mode it causes a conflict again. Do you know how I could fix this?

**Comment by andrewtavis** [comment]
Sorry for all the changes to the main branch while you were working on things, @SaurabhJamadagni! I'm a bit unsure on the issue here. As I understand it you want to remove `.light` from the text color assignment, which would allow either light or dark text colors to be assigned. Why would we add it back in?

**Comment by SaurabhJamadagni** [comment]
> Why would we add it back in?

Because if I don't add it back in, it is throwing a merge conflict. I am trying rebasing the branches. Don't know what is going on 😅

**Comment by andrewtavis** [comment]
Did that work, @SaurabhJamadagni?

**Comment by andrewtavis** [comment]
All I did was go into the merge conflict UI and remove the original line and the conflict indicators. Sorry if that was an oversimplification though :)

**Comment by SaurabhJamadagni** [comment]
> Did that work

I think it did @andrewtavis. Let me know if there are any problems. Currently, it seems like all my changes have gone through 😵‍💫

**Comment by andrewtavis** [comment]
Will bring the changes in to see if it's all working 😊 Thanks, @SaurabhJamadagni!

**Comment by SaurabhJamadagni** [comment]
> All I did was go into the merge conflict UI and remove the original line and the conflict indicators. Sorry if that was an oversimplification though :)

No worries. I think in an attempt to solve it myself, I think I was making conflicting changes myself as well. Seems like its fixed though. Sorry about the bombarding commit messages.

**Comment by andrewtavis** [comment]
No stress! 😎 Will check this now 🙃

**Comment by andrewtavis** [comment]
Looks great, @SaurabhJamadagni! Dark mode! 🌔 

Minor questions/comments:

- It doesn't look like we're switching the color of the arrows and other icons in the keyboard installation steps? Same for the link text, which should probably be made into a variable?
- If memory serves me, switching the icons in the top right is likely a bit annoying/impossible as the colors are hard coded... Do you want to remove them all for now and just put the `Go to Settings` button from the [designs](https://www.figma.com/file/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=458%3A1320&t=6AhTvOgFCxxgCdbJ-1) in the top right of the keyboard install flow?

Things I'll do after (no stress on this!):

- I think the text on the orange button should be medium and only the first letter should be capitalized.

Thanks for all the work on this, @SaurabhJamadagni!!

**Comment by SaurabhJamadagni** [comment]
> It doesn't look like we're switching the color of the arrows and other icons in the keyboard installation steps? Same for the link text, which should probably be made into a variable?

Yes @andrewtavis. The problem with those is that they are images. Thus they don't have any color variable associated with them that can be dynamic. The link colors or symbols like the globe could be changed though with some workaround. 

I was also thinking the same. This was more of a temporary solution as I planned to add more image variations that switch on dark mode when we build the full fledged menu. What do you think? We could do the button like in the design file, but currently the entire section itself is like a giant button that takes us to the Settings. So I thought it would be redundant.

**Comment by SaurabhJamadagni** [comment]
Hey @andrewtavis, could you check these changes that I pushed right now? I added alternate images for the dark mode. Apparently like color sets, we can have alternate sets for images too. Let me know if this can work instead of getting rid of it completely for now.

**Review by andrewtavis — APPROVED** [review]
Looks beautiful, @SaurabhJamadagni! Great work 😊

Will do those minor changes I was talking about above and then close the issue :)

Thanks for this! ☀️🌙

**Pull request merged**
