### PR TITLE
Remove accent characters menu option from i pads 477

### PR DESCRIPTION
**Pull request by fabulouiOS-monk**
### Contributor checklist

- [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Implemented a check for iPad to remove **Layout** section from langSpecific settings.

### Related issue

- #477

### CODE REVIEW

**Comment by fabulouiOS-monk** [comment]
@andrewtavis Please review PR, and check whether this is what you wanted.

**Comment by andrewtavis** [comment]
Hey @fabulouiOS-monk 👋 Checking on this: Are we checking if there are no menu options and then removing it if so, or just removing it for iPads? The latter works well for now, but there will be options for this for iPads in the future, so the best thing would be to remove the option from iPads - this dropping the total options to 0 - and then write something that automatically removes it :)

**Comment by fabulouiOS-monk** [comment]
@andrewtavis currently we are removing the whole section if device in question is iPAD.

**Comment by fabulouiOS-monk** [comment]
@andrewtavis, Added condition to check which menu option it is based on **sectionState**, and if there are no section we will remove the whole **Layout**.

**Comment by andrewtavis** [comment]
Just sent along a basic file reformat and also changed `MARK: -` to `MARK:` throughout the codebase as marks work without the dashes, so I don't see why we'd keep them 🤷‍♂️😊

**Review by andrewtavis — APPROVED** [review]
Thanks so much for pulling this through, @fabulouiOS-monk! Am going to do the data work now and send off v3.1 as soon as I can 🚀 So amazing to get the quick and effective help to get the new version out!

**Pull request merged**
